<?php
/**
 * @file
 */
include_once 'easyddb_ipe_filter.features.inc';


/**
 * Implements hook_menu().
 */
function easyddb_ipe_filter_menu() {
  $items['admin/config/user-interface/ipe-filter'] = array(
    'title' => 'IPE pane filter settings',
    'description' => 'Configure IPE filter default options.',
    'weight' => 1,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('easyddb_ipe_filter_default_settings'),
    'access arguments' => array('access administration pages'),
    'file' => 'easyddb_ipe_filter.admin.inc',
  );
  $items['admin/config/user-interface/ipe-filter/default'] = array(
    'title' => 'Settings',
    'description' => 'Default settings for IPE filter',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 1,
  );
  $items['admin/config/user-interface/ipe-filter/panes'] = array(
    'title' => 'IPE pane filter',
    'description' => 'Choose what content should be displayed on the add content modal page.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('easyddb_ipe_filter_admin_panes'),
    'access arguments' => array('access administration pages'),
    'file' => 'easyddb_ipe_filter.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 2,
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function easyddb_ipe_filter_theme() {
  return array(
    'easyddb_ipe_filter_table' => array(
      'render element' => 'form',
    ),
  );
}

/**
 * Implements theme_hook().
 */
function theme_easyddb_ipe_filter_table($variables) {
  $form = $variables['form'];
  $header = $form['#header'];

  $content = array(
    'header' => $header,
    'rows' => array(),
  );
  foreach (element_children($form) as $row_index) {
    if (isset($form[$row_index]['title'])) {
      $content['rows'][] = array(
        drupal_render($form[$row_index]['title']),
        drupal_render($form[$row_index]['value']),
      );
    }
    else {
      $content['rows'][] = array(array(
        'data' => drupal_render($form[$row_index]),
        'colspan' => 2,
        'header' => TRUE,
      ));
    }
  }
  $output = theme('table', $content);
  $output .= drupal_render_children($form);
  return $output;
}

/**
 * Impalements hook_theme_registry_alter().
 */
function easyddb_ipe_filter_theme_registry_alter(&$registry) {
  $registry['panels_ipe_add_pane_button']['function'] = '_easyddb_ipe_filter_callback';
}

/**
 * Filter panes callback
 */
function _easyddb_ipe_filter_callback($vars) {
  global $user;
  $ipe_roles = variable_get('easyddb_ipe_filter_roles', array());
  $roles = array_intersect(array_keys($user->roles), $ipe_roles);

  $assets_loaded = &drupal_static('ipe_assets_loaded', FALSE);
  $settings = variable_get('easyddb_ipe_filter_table', array());
  $region_id  = $vars['region_id'];
  $renderer = $vars['renderer'];

  $buttons = array();
  $menu_width = 300;
  $attributes = array(
    'class' => 'ctools-use-modal',
    'style' => 'width: ' . $menu_width . 'px; height: auto',
  );

  foreach ($settings as $subtype_name => $setting) {
    if ($setting['value'] == 1) {
      $buttons[] = l($setting['delta'], $renderer->get_url('add-pane', $region_id, $setting['type'], $setting['subtype']), array('attributes' => $attributes));
    }
  }

  $buttons = '<div id="ipe-add-' . $region_id . '" class="panels-ipe-newblock ipe-popup hide">' . theme('item_list', array('items' => $buttons)) . '</div>';

  if (!$assets_loaded) {
    $mod_path = drupal_get_path('module', 'easyddb_ipe_filter');
    drupal_add_js($mod_path . '/js/ipe.js', 'file');
    drupal_add_css($mod_path . '/css/ipe.css', 'file');
    $assets_loaded = TRUE;
  }

  $links = l(t('Add'), NULL, array(
    'attributes' => array(
      'class' => 'ipe-trigger',
      'target_region' => $region_id
    )
  ));

  // If user roles are not set then display default ipe modal window.
  if (empty($roles)) {
    $attributes = array(
      'class' => array('panels-ipe-linkbar', 'inline'),
    );
    $links = theme('links', array('links' => $vars['links'], 'attributes' => $attributes));
    $buttons = '';
  }

  return '<div class="panels-ipe-newblock panels-ipe-on">' . $links . '</div>' . $buttons;
}
